### ISSUE TITLE
Loving the plugin

### ISSUE THREAD

**Issue by Ismael-GT** [iBuseWinner/Reputation#1]
Helloo!

I woud like to know when this feature will be released 💯 
"/rep top — show top players by reputation (ADDED IN FUTURE UPDATES)"

Also, will be great if you add a placeholder to get the names tops, and I will add it to my menu plugin!

%rep_top_1%
%rep_top_2%
%rep_top_3%

1-10 or 1-unlimited

**Comment by iBuseWinner** [comment]
Hello. Thank you for such kind words <3.
I think I will completely add this command in 2-3 days.
And of course, I’ll add placeholders for the top.

**Comment by iBuseWinner** [comment]
Added in the version 2.1.
You can download it now <3
