### ISSUE TITLE
Безлимитная репутация.

### ISSUE THREAD

**Issue by karamzyatina** [iBuseWinner/Reputation#11]
Здравствуй, нашёл такой баг: Если включить can-unlimited-reps: true, то после того, как игрок отдаст очко репутации другому игроку, он не сможет снова его выдать т.к уже выдал. Собственно она не работает. Так же не работает /rep undo.
Хотелось бы ещё увидеть более понятный файл с данными об игроке. Если менять вручную, результата не будет, плагин устанавливает предыдущие данные об игроках.

**Comment by karamzyatina** [comment]
Репутацию можно выдавать бесконечность раз, но за всю игру определённому игроку можно выдать только 1 раз. Т.е если я выдал игроку Player1 1 очко,  я могу выдать игрокам Player2-10, при этом Player1 больше не сможет получить от меня репутацию. Так будет понятнее

**Comment by iBuseWinner** [comment]
> Если менять вручную, результата не будет, плагин устанавливает предыдущие данные об игроках.

Потому что сервер сохраняет свои значения. Менять можно через админскую команду.
Сейчас у меня нет времени заниматься разработкой плагина, но в планах есть его перепись. Как только освобожусь, тогда и посмотрю, а сейчас ничего обещать не могу.

**Comment by iBuseWinner** [comment]
Плагин скоро получит обновление, написан будет плагин с нуля, поэтому этой функции не будет на первых версиях. Что будет дальше - узнаем в будущем.
