### ISSUE TITLE
PlaceholderAPI, отрицательная реп

### ISSUE THREAD

**Issue by ItzIsonn** [iBuseWinner/Reputation#13]
Не видит плэйсхолдеры, выводит %reputation_reputation%. Не отображает меня в списке лидеров.

Также сделайте, чтобы можно было устанавливать отрицательную репутацию

**Comment by iBuseWinner** [comment]
Доброго утра.
Сразу скажу по поводу отрицательной репутации - обновление было выложено вчера, должно работать.
По поводу PlaceholderAPI - есть ли какие-то ошибки в консоли при запуске плагина или при попытке использовать /papi parse me %reputation_reputation%?

**Comment by ItzIsonn** [comment]
Ошибок нет, просто не хочет выводить.

А при попытке установить отриц. реп. выводит "Должно быть числом"

**Comment by ItzIsonn** [comment]
Вот, что выводит

https://user-images.githubusercontent.com/123226827/213845180-8406be90-fade-4536-ba37-5ec776ea5b09.mp4

**Comment by iBuseWinner** [comment]
Установить через админскую команду, понял. Поправлю в течение дня.
С PlaceholderAPI интересная ситуация. Такое происходит с самого запуска сервера или после /papi reload?

**Comment by ItzIsonn** [comment]
Да, после /papi reload

**Comment by iBuseWinner** [comment]
Посмотрю, что можно с этим сделать.
