### ISSUE TITLE
Не работает изменения титулов

### ISSUE THREAD

**Issue by Mi-Di-7** [iBuseWinner/Reputation#19]
Снова здравствуйте. 

Титулы в репутации просто не работают, всё что выше первого титула не считывается! Я перепробовала всё: И от хранения данных в базе отказалась, и меняла местами разные значения, и тру/фолсы, в какой-то момент я даже задумалась, что может надо иметь ровное число репутации с данными в конфиге, но даже это не сработало, даже перезапустив сервер ничего не поменялось. У меня искреннее непонимание ситуации, учитывая, что, похоже, у других людей всё работает...
![image](https://github.com/iBuseWinner/Reputation/assets/139273269/44e43fa0-44e7-4a4a-a609-d702c2c26637)
![image](https://github.com/iBuseWinner/Reputation/assets/139273269/e745d7a5-19ed-4f2e-9c7b-0d5c44f1f497)
![image](https://github.com/iBuseWinner/Reputation/assets/139273269/672a4257-f748-4a1c-8ae0-b26da210e7bc)
![image](https://github.com/iBuseWinner/Reputation/assets/139273269/7ee20f8f-d435-485e-890f-c6bba673f9ba)

Проблема оказалась решена (Как я сначала подумала, подробнее в следующем абзаце). Оказалось что при титуле с репутацией 0 он считается за абсолют, который невозможно перебить будущими титулами (Об этом не было нигде написано). Жалко около того часа времени, что я на это потратила... Если возможно измените несменяемый титул на -1, а не 0...

И снова проблема появилась. Я сначала обрадовалась, но когда мои друзья попросили повысить им репутацию, дабы проверить, репутация опять полетела ко всем чертям до первого титула. Я ничего не меняла, почему титулы опять не работают я понятия не имею... Сейчас работают только 2 титула, если меняю кол-во необходимой для второго титула репутации всё опять ломается и не работает даже он...
![image](https://github.com/iBuseWinner/Reputation/assets/139273269/0f032514-cc8b-4b48-9223-51a46fb2b9ce)
![image](https://github.com/iBuseWinner/Reputation/assets/139273269/63819e3b-202b-452b-ac74-ff41fe2b4bd1)
![image](https://github.com/iBuseWinner/Reputation/assets/139273269/43d7d557-c98a-4ecb-bedc-6a71acd6e36b)
![image](https://github.com/iBuseWinner/Reputation/assets/139273269/77ec3815-cbe6-4f97-a9f4-6e0c6711120a)

Новая информация: Оказывается титулы больше однозначных чисел не работают.
![image](https://github.com/iBuseWinner/Reputation/assets/139273269/78035d33-2848-4445-9479-3c1b84e7ac99)
![image](https://github.com/iBuseWinner/Reputation/assets/139273269/5871a69a-055b-4198-b50d-41a3b29f2bae)
![image](https://github.com/iBuseWinner/Reputation/assets/139273269/a175dad1-0e9e-4c4a-8a75-b0f367ba0ca4)
![image](https://github.com/iBuseWinner/Reputation/assets/139273269/00ddba28-8120-4772-a853-7c1d033819d5)

Есть какое-то ограничение на следующий титул? Как заставить всё нормально работать??? В этот раз максимум - 17
![image](https://github.com/iBuseWinner/Reputation/assets/139273269/4d77ade3-20f4-43ee-b1f3-c952611e4530)
![image](https://github.com/iBuseWinner/Reputation/assets/139273269/16b7f2ce-9d9f-49f8-805e-9f1ff4054b5a)
![image](https://github.com/iBuseWinner/Reputation/assets/139273269/bf471a97-9d59-494c-b45d-eaccb2313334)
![image](https://github.com/iBuseWinner/Reputation/assets/139273269/1ca6927f-bda3-4fbe-b968-02273b8f8a18)

Из разряда очередных интересных наблюдений - после рестарта репутация автоматически отключена и сведена к начальному значению, а так же похоже на каждый уровень репутации есть какое-то ограничение, которое не затрагивает следующий уровень
![image](https://github.com/iBuseWinner/Reputation/assets/139273269/d43d02e1-2a73-4788-a8db-2d0af9b2cefa)
![image](https://github.com/iBuseWinner/Reputation/assets/139273269/3b143507-aa43-40ef-bd00-0051719e0a19)

**Comment by iBuseWinner** [comment]
Можно узнать версии сервера, плагина, а так же конфигурацию config.yml (без данных от бд)?
/about - версия сервера
/about Reputation - версия плагина

**Comment by Mi-Di-7** [comment]
![image](https://github.com/iBuseWinner/Reputation/assets/139273269/b234725d-c151-4b37-aa0a-bd37ffece391)

**Comment by iBuseWinner** [comment]
Вообще, никаких ограничений я специально не закладывал в счёте титулов, но обязательно проверю с нескольких аккаунтов и с разным количеством титулов в конфигурации, но только сегодняшним утром.

**Comment by Mi-Di-7** [comment]
Ок, буду ждать результатов проверки. А так и должно быть, что после рестарта вся репутация сводится к 0 (Даже не учитывая то условие что изначальная репутация поставлена "1")?

**Comment by iBuseWinner** [comment]
Не сохраняется, то есть? Это происходит только у онлайн игроков или репутация сбрасывается у всех, даже тех, кто вышел до рестарта?

**Comment by Mi-Di-7** [comment]
У тех кто вышел до рестарта репутация остаётся сохранённой, у тех кто был во время рестарта репутация сбрасывается

**Comment by iBuseWinner** [comment]
Понял, запишу, тоже постараюсь исправить

**Comment by Mi-Di-7** [comment]
Так же со мной были два друга (Оба кикнулись во время рестарта). Стандартная репутация установлена на 1, но у одного после перезахода она была 0, а у другого 1. Мы вообще не понимаем что происходит ._.

**Comment by Mi-Di-7** [comment]
Будем ожидать результатов завтрашних тестов.

**Comment by iBuseWinner** [comment]
Всё починил, должно работать в последнем обновлении 3.0.11-БЕТА. Пожалуйста, проверьте и отпишитесь по этому поводу.
https://spigotmc.ru/resources/reputation-dajte-igrokam-pravo-vybora-luchshego-iz-nix.124/download

**Comment by iBuseWinner** [comment]
Полное описание обновления выложено на форуме: https://spigotmc.ru/resources/124/updates#resource-update-3257
