### ISSUE TITLE
Пожалуйста добавьте поддержку 1.20.4

### ISSUE THREAD

**Issue by Boatswain888** [iBuseWinner/Reputation#22]
Очень прошу добавить поддержку 1.20.4, 
[2024-05-20-6.log](https://github.com/iBuseWinner/Reputation/files/15381729/2024-05-20-6.log)
заранее благодарю!

Please add a support for 1.20.4, will be very glad, thanks!

**Comment by iBuseWinner** [comment]
Плагин работает нормально, проверено на всех версиях.
