### ISSUE TITLE
Reloading PlaceHolderAPI creates bug

### ISSUE THREAD

**Issue by shaqupl** [iBuseWinner/Reputation#5]
29.01.2021 - 00:41:15 - [TAB v2.8.10] PlaceholderAPI v2.10.9 generated an error when setting placeholder %rep_rep% for player Kuszaa
29.01.2021 - 00:41:15 - java.lang.NullPointerException: null
29.01.2021 - 00:41:15 -        at ru.buseso.spigot.free.reputation.Reputation.getOfflineRepPlayerByNick(Reputation.java:206)
29.01.2021 - 00:41:15 -        at ru.buseso.spigot.free.reputation.Reputation.getRepPlayerByNick(Reputation.java:226)
29.01.2021 - 00:41:15 -        at ru.buseso.spigot.free.reputation.Utils.RepExpansion.onPlaceholderRequest(RepExpansion.java:33)
29.01.2021 - 00:41:15 -        at me.clip.placeholderapi.PlaceholderHook.onRequest(PlaceholderHook.java:31)
29.01.2021 - 00:41:15 -        at me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:156)
29.01.2021 - 00:41:15 -        at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:69)
29.01.2021 - 00:41:15 -        at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:97)
29.01.2021 - 00:41:15 -        at me.neznamy.tab.platforms.bukkit.BukkitPlatform.setPlaceholders(BukkitPlatform.java:206)
29.01.2021 - 00:41:15 -        at me.neznamy.tab.platforms.bukkit.BukkitPlatform$2.get(BukkitPlatform.java:182)
29.01.2021 - 00:41:15 -        at me.neznamy.tab.shared.placeholders.PlayerPlaceholder.update(PlayerPlaceholder.java:22)
29.01.2021 - 00:41:15 -        at me.neznamy.tab.shared.features.PlaceholderManager$1.run(PlaceholderManager.java:99)
29.01.2021 - 00:41:15 -        at me.neznamy.tab.shared.cpu.CPUManager$4.run(CPUManager.java:119)
29.01.2021 - 00:41:15 -        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
29.01.2021 - 00:41:15 -        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
29.01.2021 - 00:41:15 -        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
29.01.2021 - 00:41:15 -        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
29.01.2021 - 00:41:15 -        at java.lang.Thread.run(Thread.java:748)

/papi reload make reputation placeholders go %rep_rep% instead of value.

**Comment by iBuseWinner** [comment]
Hello. I'll try to fix it this weekends if I will have time

**Comment by iBuseWinner** [comment]
**/about Reputation**
Please say version.

**Comment by iBuseWinner** [comment]
Hello. Fixed MySQL.
Check it please.

Download 2.3 (Beta so used google drive): https://drive.google.com/file/d/1uV5C1yr6jBNGCW2jY2YnO7QBcXtKw0gL/view?usp=sharing
