### ISSUE TITLE
[Предложение] Права на управление репутацией

### ISSUE THREAD

**Issue by Thin-Troll** [iBuseWinner/Reputation#8]
Необходим пермишенс на стандартные команды (см. скрин)
Пермишенс: rep.player

![image](https://user-images.githubusercontent.com/61376903/126475970-f2598bb9-85a5-4048-b1af-3cb5244395f1.png)

**Comment by iBuseWinner** [comment]
Будет реализовано!

**Comment by Thin-Troll** [comment]
Если ты все таки решил заняться им, то еще пару замечание и пожеланий напишу)
1. Предложение: Реализуй возможность выдачи репутации только тем, кто отыграл N времени (указывается в конфиге), таким образом можно исключить накрутку с фейков;
2. Баг: Если выдать репутацию и потом ее забрать, больше данному игроку нельзя изменять репутацию.

Версия плагина 2.2
Версия ядра Paper 1.12.2 build 1620
и Paper 1.17.1 build 408

**Comment by iBuseWinner** [comment]
Плагин скоро получит обновление, написан будет плагин с нуля, поэтому этой функции не будет на первых версиях. Что будет дальше - узнаем в будущем.
